from telethon import events
import random, re
from userbot.utils import admin_cmd
import asyncio 
 
 
 
@borg.on(admin_cmd("جرس"))
async def _(event):
     if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await event.edit("🔔")
        await asyncio.sleep(0.4)
        await event.edit(" 🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.4)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
        await event.edit("🔔")
        await asyncio.sleep(0.6)
        await event.edit("🔕")
        await asyncio.sleep(0.6)
